services:
  - type: web
    name: threatintel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true 